### ISSUE TITLE
Logging mechanism in htsget server

### ISSUE THREAD

**Issue by dbampalikis** [GenomicDataInfrastructure/starter-kit-htsget#5]
As a GDI-developer
I want to have meaningful logs when running the htsget server
to be able to debug issues that might come up during deployment

The logs for the htsget server are currently in debug state and need to be improved in order to provide useful information and to allow for different levels of verbosity.

**Comment by nanjiangshu** [comment]
This issue is closed by the PR https://github.com/NBISweden/htsget-refserver/pull/1
