### ISSUE TITLE
Handle partial file requests in htsget

### ISSUE THREAD

**Issue by dbampalikis** [GenomicDataInfrastructure/starter-kit-htsget#6]
As a GDI user
I want the htsget server to return the full file if I request some parts of it
in order to avoid error with not supported functionality

Currently the Go version of the htsget server cannot return parts of files and this should be handled in some way, instead of returning an error.
One possible way would be to "translate" the request and return the full file instead.

**Comment by d-salgado** [comment]
Hi @dbampalikis are you sure that a GDI user wants the full file if he only request a region such as a chromosome ?
I believe that something in between would be more convenient, for instance the htsget server can return the full file, but an API between the HTSGet Server and the user will only return the appropriated region.

**Comment by dbampalikis** [comment]
Hello @d-salgado , you are right that the end goal is to allow for partial access to the files. According to the [specifications](http://samtools.github.io/hts-specs/htsget.html), this should be supported by the htsget server. Unfortunately, the [go reference server](https://github.com/ga4gh/htsget-refserver) is abandoned for some time and the requests for a specific region are not handled properly. Therefore, our idea is to patch this by returning only whole files for the first starter-kit version and work on fixing the functionality as soon as possible!
